name: Build LaTeX document
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document for resume
        uses: xu-cheng/latex-action@master
        with:
          root_file: fan_jin_resume.tex
          args: -xelatex -file-line-error -interaction=nonstopmode
          extra_packages: moderncv
      - name: Azure log in
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Upload PDF to Azure Blob
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload \
              --overwrite \
              --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
              --container-name ${{ secrets.AZURE_STORAGE_CONTAINER }} \
              --name fan_jin_resume.pdf \
              --file fan_jin_resume.pdf \
              --auth-mode login
            echo "Deploy Success"
