name: Build LaTeX document
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document for resume
        uses: xu-cheng/latex-action@master
        with:
          root_file: fan_jin_resume.tex
          args: -xelatex -file-line-error -interaction=nonstopmode
          extra_packages: moderncv
      - name: Deploy PDF to my github pages
        env:
          PAGES_URL: ${{ secrets.PAGES_URL }}
          KEY_US: ${{ secrets.KEY_US }}
        run: |
          git clone ${PAGES_URL}
          cd goldsail.github.io
          cp ../*.pdf ./
          git config --global user.name "Fan JIN"
          git config --global user.email "kingium@outlook.com"
          git add fan_jin_resume.pdf
          git commit -am "update resume"
          git push
          cd ..
      - name: Deplot PDF to CN server
        uses: horochx/deploy-via-scp@master
        with:
          local: fan_jin_resume.pdf
          remote: ${{ secrets.REMOTE_CN }}
          host: ${{ secrets.HOST_CN }}
          port: ${{ secrets.PORT_CN }}
          user: ${{ secrets.USER_CN }}
          key: ${{ secrets.KEY_CN }}
      - name: Deplot PDF to US server
        uses: horochx/deploy-via-scp@master
        with:
          local: fan_jin_resume.pdf
          remote: ${{ secrets.REMOTE_US }}
          host: ${{ secrets.HOST_US }}
          port: ${{ secrets.PORT_US }}
          user: ${{ secrets.USER_US }}
          key: ${{ secrets.KEY_US }}
