name: Build LaTeX document
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document for resume
        uses: xu-cheng/latex-action@master
        with:
          root_file: fan_jin_resume.tex
          args: -xelatex -file-line-error -interaction=nonstopmode
          extra_packages: moderncv
      - name: Deplot PDF to US server
        uses: horochx/deploy-via-scp@master
        with:
          local: fan_jin_resume.pdf
          remote: ${{ secrets.REMOTE_US }}
          host: ${{ secrets.HOST_US }}
          port: ${{ secrets.PORT_US }}
          user: ${{ secrets.USER_US }}
          key: ${{ secrets.KEY_US }}
